apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kilo-ui
resources:
- namespace.yaml
- manifests/kilosubspace.yaml
- manifests/kilo-wg-gen-web-oidc-rbac.yaml
- manifests/kilo-wg-gen-web-oidc-rbac-headless.yaml
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Service
  metadata:
    name: kilo-wg-gen-web
  spec:
      clusterIP:
- |-
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: kilo-wg-gen-web
  spec:
    template:
      spec:
        volumes:
        - name: tmp-volume
          $patch: delete
