apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-main
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgAuf8P8IdZDJ350qPB6GMXsDaJ6/+At0q48uQbeOO4z60ssC4qLcfgNQbgh2XHX4CZGpWZPTbMf4rUj++s+aeYhLsr9y2Uuo1uaVKZ5beSB09x47MnsSG7ACGnRjLvS8tU21GXKOZWTOHRhcPQAAWOAxJqwwnLUJDWiYHMXon8xFHzKhvRpbul8BgRP6zZjcKz83g6g7p4RnXrvE48rSZ6vb+425AcsCzJSctVP0u3SDyN9awl4chYChKqm22K6RYvopDDQqYeMqLkZK/U7472JElKyxObY2q18W6cfr5o2spLdzSiexDtApGjnpxVIVqhaoXv01W/FxCufHz817qJUz+v8OW2pU4uQ/GuyIeD019PnZqYJ7NHqrnY1N8ADfKtxW6iwczMZG3T5lqhnOZGYidybHA2V1KoYjm5ZVcXHiiUfT6TQAS0URqaZa5kBkG1zphgSjEhSz+yweMov0zuXdjwg3hncMnrvYYRb6QppxUqOlqrZb3u3TCTmY2V31hMLcppcKlc2PSi0Tzw6Z/gJ6J4tdtl85/0sy8kj8ybi6ds8so12MOqTN2XCVtn1rR6KhWEbMh5QLBUVgvDEO0fVrE19PXOSizoiUpTlomGTtJTaCS3HpSAsjrAfv3NPAeOUNJUCI9TF7aF7Xo9GZIcd4iAmWirNA6XBjWaLVNseRL6IpGNZenVLMl43LVcEzpUQp4m25TUh/c3B3A2yzmI1/i2l5uYMG4Orb9Szd0MR9WZKlp7Olinj/Zu77ajUsL8oi3CmNNcvqsqSH6QG+tVHt0ZKEy92IBbNuL8zDjM/lNgmQNiPl3RQLzt+WmrdpVzpP5xtZEgzHAwjqkqwsvyJhVx98QA+9wHPCLHqVaaD8U/hpYMuVTRLJSlY3vx0KqfOlFseK3BWLl7c0sloDKm986GjbQTy4fVWyoYcSIhA+wTBe0sSXLIJ9mrOSiI+7xenZ6Awsuj6ds924tvSosWgzIYuUtW5zw8RwCNMSa4zZQRMzpE9dOrx7NMJh8SP2x+7BrM+vzSLOcBjrmzeFnihyLv2FCZudEBzqOaqUhKxzFzj4ogrD4toSYBnyYCKE2Asp/9SJAbWHGaIfG+TTTDIB/cPTnb4MO7PMo9FV4jKEdE6+XT/yYjZlneihPIZkMpYNNG+oJYwsUsiYHGhtW20Cr7NboP2HFuHF3h0HQW65kUYtYRpUjBCpl8gHX0d6g2TwbxtcRi0C8FyH7Y7UJPvCCt0A95g5mphexxQExR/bZlLrofs+TCWORTls1qWSPasX58wO35HAAGhqpINiDoNWOeXH8lo6UI5DCuYpmshL0IXmxLQsFS6AsM6UC9e6bQR9/hgrwNPxb0a+ce+l2Uu4dofrJUJj0Vd0Ym4VxjSSoUg3NUBLTQbDJSC51LDFr7WiVQ08egtHZ/BMWBKIg4pHmhZc3/8JKgahFLGW9C+DiOO8NoCkish2enprEeIaFZFBHXOTxQ1wN7sEYsmdc3dLVGWJLtfq7TFk8EPyzLzoC5bxPIliXWqx1d381SM76tapZvlVKpi5VKkKxYfcJ0tTUWliqrj5CHbJ3wkk6bMgj3TrneDT+HE2x27p9M07C7THIA3NiS2SON2qjI0kg==
  template:
    metadata:
      creationTimestamp: null
      labels:
        alertmanager: main
        app.kubernetes.io/component: alert-router
        app.kubernetes.io/name: alertmanager
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 0.21.0
      name: alertmanager-main
      namespace: monitoring
    type: Opaque

