apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-main
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgBKx+YPTwADFRuzJfDHoYZeofbP8bRLEuLojqAvZBomYMZdQU4rpWkOR9N/rUL2pqezhpFV5mo7c3SCYSe90B6s5N6ZxkkUvfNAN8qjceYJIqJRYVrXAjtpNcvu0FIKb+/vQN6cTH925KCA/SiDK5zjpBQ6JzwBfQJe4gyYW5Yn6LRzRGZz4pm9EBTfU2WgbPgKU4EV8UXry1XzqJrSDLQeUotKrSKYZcBg1Z8FeSIHR5tVCktOVxLCCUIcC/dZmVMk5piDas+4o0DJ31pPhpuFLFHHoIcBGtrz86frY3LVFsJ2Xea5MWYqSlBmPba0jIOvuCLQ9pEvTa7n6GeFCCPQbSA1c2BLHRNrVtk6Yn/lxBHSBJxBC8j4ZcrUoACuilA4L2kHbAP5JUOsmPzYiAHyzvjzMaXf73XZ1B2KNIPlWqqVoBN+LLupe2+CK9OdbnxR8AuLt6eT+Lk3B3pHbtBP1te48FBQxHDwIYMaSeAdAgD/yw5O6JZs8GwUde0CorrqkZzeYC/h6QGL49hzALDsVBnhm+zix11xlU6vmEJIRW7ExzitTJ/qvwv9kTYsqqNVNfdI1hqYCqt+iKbBdkJdsITy9p0S8M4CpjbPhbKkXF/fs6zq3zvdhyMpjkDG7emy1blBdIyAGdfcwrGpDaWC3joUnWQ2HabSFh9VX3E1uVlC9uYOImGaVxiUTj01ZIzR2zTZ4yMof9l6jNO2tF8TbpHo/rdFKa5xsl2fJs7vi0OEM7c5xUPqjXGsvCLAFJJ5dieDcJ6ukIUlU6061unA3Yo301skFQT5WqdNuS9QpbqkWJGQrv49RQ/eYUT4Vo2Q6ctkydx9JVt9WV++/+5eK6/hDKCBeDybD0Xxk4MSkeQY19QVnx0OydG5NdNU+O69FobkCTKeVHhdZatKriBfKTRWhOmf8jf/s4N42r/Y244LxqCaxPZLxr5ohJgo4ZAUnjRr9MHpX3RnQ9Fz0mbR7qz1eiH75c4usGS0ZU7HOnxH9uDKQ0cyTgniBSGPaMWbdDK7dHe8/2YYnrqZifVoPL/y9gSqxt7BTcSKX1aKsH1a4j7DK6tVGP4Ompzr+RGQKvRZhYqXy98jmT2gSUAmsjKOl1L8DmoevjkfxdB24hytx5z8d35W2/tMSZw5GVFDtxUoJxGcvtNfzQJujvjB6MRT+xWNeilYDorcc8miPCcR8UqJg9dNxk6QMnEQMvzRzfCgorJZAkXY0TUpSi0awcwel0TcPACovjj7SI/rZrwylJ1OVOleRpRbP8GXxjQrhG/7FklSHAsXJ7blbGsEcCdxm4oi9sD3GaO3Psn0T35X++TLpPIecb6reARE7aYsCcD3UKgwqdeJRd6jaJSPCcc8x+8RmG4N9STmta9GgJB7o4VBkbNRnPMquWb2vgq50cZ9NP1L+yhudPksxCRPR4GYgJqoHRYCYr5aTkWz5QUiNqp4nytwOz3FenwVNub59H2YhkAEH4lzm6zdj+PDbI2a/4uLPn7+hCUloyxyYNc6WdjE7eOnDokdN7fIm3+APDred8Xt2ddvjIg4DFJi3eiChXxikQAaSzwAuMhTa9cWNZqlr/F5IE/EnEuA/2xO+HW1ZEqfifxpTvQ2vw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        alertmanager: main
        app.kubernetes.io/component: alert-router
        app.kubernetes.io/name: alertmanager
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 0.22.2
      name: alertmanager-main
      namespace: monitoring
    type: Opaque

