apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: prometheus.k.squat.ai
  name: prometheus-k8s
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 80
    targetPort: web
