apiVersion: apps/v1
kind: Deployment
metadata:
  name: servor
  labels:
    app.kubernetes.io/name: servor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: servor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: servor
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - pi-blaster
            topologyKey: kubernetes.io/hostname
      containers:
      - name: servor
        imagePullPolicy: Always
        image: squat/servor:e8bb47ad6a035fe1bb5428790a865e0da51893a8
        args:
        - --listen=0.0.0.0:8080
        - --min=0.03
        - --max=0.26
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev
          mountPath: /dev
      volumes:
      - name: dev
        hostPath:
          path: /dev
---
apiVersion: v1
kind: Service
metadata:
  name: servor
  annotations:
    external-dns.alpha.kubernetes.io/hostname: servor.k.squat.ai
  labels:
    app.kubernetes.io/name: servor
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: servor
