apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: unpoller
spec:
  podMetricsEndpoints:
  - interval: 15s
    port: tcp
    path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: unpoller
