apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
- manifests/crds.yaml
- manifests/kilo.yaml
- manifests/podmonitor.yaml
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/2
      value: --subnet=10.5.1.0/24
  target:
    kind: DaemonSet
    name: kilo
