apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: ["manifests/rbac.authorization.k8s.io_v1_clusterrolebinding_ingress-nginx-admission.yaml", "manifests/rbac.authorization.k8s.io_v1_clusterrole_ingress-nginx-admission.yaml", "manifests/admissionregistration.k8s.io_v1_validatingwebhookconfiguration_ingress-nginx-admission.yaml", "manifests/v1_serviceaccount_ingress-nginx.yaml", "manifests/batch_v1_job_ingress-nginx-admission-patch.yaml", "manifests/v1_serviceaccount_ingress-nginx-admission.yaml", "manifests/v1_configmap_ingress-nginx-controller.yaml", "manifests/rbac.authorization.k8s.io_v1_clusterrolebinding_ingress-nginx.yaml", "manifests/rbac.authorization.k8s.io_v1_role_ingress-nginx-admission.yaml", "manifests/rbac.authorization.k8s.io_v1_rolebinding_ingress-nginx-admission.yaml", "manifests/rbac.authorization.k8s.io_v1_role_ingress-nginx.yaml", "manifests/rbac.authorization.k8s.io_v1_clusterrole_ingress-nginx.yaml", "manifests/v1_service_ingress-nginx-controller.yaml", "manifests/v1_service_ingress-nginx-controller-admission.yaml", "manifests/batch_v1_job_ingress-nginx-admission-create.yaml", "manifests/networking.k8s.io_v1_ingressclass_nginx.yaml", "manifests/v1_namespace_ingress-nginx.yaml", "manifests/apps_v1_deployment_ingress-nginx-controller.yaml", "manifests/rbac.authorization.k8s.io_v1_rolebinding_ingress-nginx.yaml"]
commonLabels:
  helm.sh/chart:
  app.kubernetes.io/managed-by:
patchesStrategicMerge:
- |-
  apiVersion: networking.k8s.io/v1
  kind: IngressClass
  metadata:
    name: nginx
    annotations:
      ingressclass.kubernetes.io/is-default-class: "true"
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ingress-nginx-controller
    namespace: ingress-nginx
  spec:
    template:
      spec:
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
- |-
  apiVersion: v1
  kind: Service
  metadata:
    name: ingress-nginx-controller
    namespace: ingress-nginx
  spec:
    type: ClusterIP
patchesJSON6902:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --report-node-internal-ip-address
  target:
    kind: Deployment
    name: ingress-nginx-controller
- patch: |-
    - op: replace
      path: /kind
      value: DaemonSet
  target:
    kind: Deployment
    name: ingress-nginx-controller
