apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: adjacency-curl
  name: adjacency-curl
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: adjacency-curl
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: adjacency-curl
        spec:
          containers:
          - name: curl
            image: curlimages/curl
            command:
            - /bin/sh
            - -c
            - json="$(curl --fail --silent --show-error adjacency.adjacency.svc.cluster.local:8080?format=json)" && [ $(echo "$json" | grep -o '],"ok":\w*false' | wc -l) -eq 0 ] && curl --fail $HEALTHCHECKS_URL
            env:
            - name: HEALTHCHECKS_URL
              valueFrom:
                secretKeyRef:
                  name: adjacency
                  key: HEALTHCHECKS_URL
          restartPolicy: Never
