apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: adjacency
  namespace: adjacency
spec:
  encryptedData:
    HEALTHCHECKS_URL: AgBcDEvTfy+vaamxFztsi6apk769gTNAkDuTVaM7Uit365BiQpkX+D1btFcdF+55sH9S9j5tzN4PGzH29fOd5exl21s3ECCBN/9EvAFyOp1WnfcrROxZ314dFsZNbxfGCQC/CDleLGpcxyRqXeR3A5ey2tapeOP/TnISsB2cxpm+T4qK8wkDQ/RmeoVN1rT7bay1QDvdcZJerBDcw5qjum98x5CCwtiui8fipf1lK1jRwcrwWXdOiGPgsUcmEQhBWfxdYEGwbkIlnbGlHtDWA9hrO7aDXsdQC8zXgLhS/PHPY7t+NBls7K+bPTLg/Wy++UHKcW4w0/sLLEh6HHa8OEpsBy29UsKXtPK4e6oVLoNYU0GFOsygkvs9LrXpv1eAUmY0Fz7Hf7DyA9PsZqce5ZTltCaOC90XKh8RAwOvHZuO2DOtpmNZCiGeXR+BZQcF+uA7LWe0LGfuNZVeTbM2GqrnOsDZs5Z7b+ujnoW4b+mnz8E00ePguZdqYwA8J74d/92lRcmyO9R//+RNOj13HTwQFG1VeJSYAz8yFEPP16+vgKELvGa0OmsmJjAsnlcAqIRfokQmIHyqgZ9WK5wa/hOlU+cw/UgDOa4HioGyOWc4HErbehz/FuyogJl0VNYf/QWPfq/YlEtMXZQNoxtlpcUfXz5h/P7oB31depQFL/+NG6B2F3RWewiu09eeX3rOnn1mS7HWUE93CUt9XbiglrxHpBKAFdBU93vPQKp1Jb+lT7HTWZcUTeGdKQEO54WaiUXei96Lx5S3Gw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: adjacency
      namespace: adjacency

