apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
bases:
- ../../base/kilo
patchesJSON6902:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/2
      value: --subnet=10.5.1.0/24
  target:
    kind: DaemonSet
    name: kilo
