apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patchesJSON6902:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/1/command/2
      value: '1'
  target:
    kind: StatefulSet
    name: line-in
