apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    CLOUDFLARE_API_KEY: AgAIwesOgckm/C53anDDZTJb+G7n/+N7HoWXjzfDE7PJ1YEzkAwLc02SQtS1/ddwwFMxgxZx0skzY3HnH0LqFB3f0TBsnYplY+NWfEQM2irYy8agsrqBa6/qUkbm/kwox9OFDzR0QhfuPuVLfgQnB5ZIwzSfB1qPnExRxCwmdVE1MR/Zi23h2paN+cmRu4kpOaTKXgo4pWw6BtOwZqTbseNudc/ySqfL2inzn/m8zW79hjT2XqJXVl7f3KrUmqjSzettJeowkFbZxXK/ncmP945t1INZWIMj8BVc9d/MvzgivO/R99HgKYx1hayAsj0dGw+XHH983kg5YXXZvr9aeXUGBihmBAj2c3impfctOlxXNPMlU97wGgP4UQ5PP5Ek6HaWfPbss+/EuSDKNHk/aj5L8OuHfTbk3fEZyIq/B7V0C7EmjH9jXxAqiYkFObUg82E5m9m3Us+25A+N9SRoiu8c6kGe9uGjedOGsghC2xoCrJ+NU03N5J7OeaWSsQJqZC5QwU4K3l5MD3S4sU7+z+w4XGtj3f/Hm+CDnYGDmVRK+P7p5CDHNYTStM1/RoOrhehrKS1ORhpzwf/qxp4a9bdo2auGaG6RmwBmBOFVTZ3Dl5+wSnh2DxUrtBnBpFjTDzsh92ix8BPrhmj6NRrgUHEKJ9qNttttSVWOK29L2oHVr1/qJftD2bLJx63b6T2imdq06FbLclE9JV1+MAFHUyB1FpF2A7y++2YBzNwQ5LbOgSjAAXgK
    CLOUDFLARE_EMAIL: AgAlPDkP4D7tGWUD5iYJ2onoVfbT99/NjkjugtUJkjuDk8bkIQAcBmU5C4ZGDgicHBIDYAJyBzL7va3no9vAOSvwvNWIqXfZDDRMoptvqmIGOX9Id9BCVwqdASOEnbID0IY/aKTwINSMiJdmyHsQeGU4ZNVxP8Z+ci6OyJqKd9rPAp3HvH/SPrrOFuuhKl3a5eXK3vDUeT+UiipT0a/S3j2chP6W6ED5UlxOH0MP0SZvjR15vmfdzOwND9RdN93wi9fbJ41gqVcG5M+UEA0QSXBMb2r3HLR24ueypzPuX0/vT6j3OEx33N3l47gNeON0+6HXo7kDF2pbV1R7AGfoW8Zl7Hx0ThiFeTqxgjjmYPQoq30AYvTbCy1pxRqre/lWt74mW74ztKe0XJzjeG5k6xOvOG10x9DsZihu9ypwVI9lKxMMX1J4EinyPOxYA1DbSHvZSpn10NwsHOOklnEaj2cRW+JGKN9lTSa6HVqrd/+splCyOMSOQ/HLG0EZv+AbipNW1OGCKa8KZZ9chIcKwn5HPtGeKGNib4fz4+eEJ0LWnP0lys16p2w0NgU/tDy/i1rMafikrhLJ3Nxsfsi2a04aWb3oO7i8UC5xE60hpKbfd1qxqYEOfTtEJEPEeGl9ymyNI15OKU6XtO6WQphJsUjA+1rq8xS7w4SH6Agj8/w/XBlEVEKtFP0GLIPzDVQ9EDOFfb8/AD5Tp3XVwRlPuiNE6w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: external-dns

