apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    CLOUDFLARE_API_KEY: AgA66Hh1gCIlK8YU6QiJYVSFwiInq+1od1G7LE0cyxUBIJXkm/uC/+Pxdmte9q0AMqjkjUFmncSDTUzN61wV4abnUxfcJbOM8e5zZr+AHlzeLHWeb+O8Nfd6YS8L8ANCTyD+Odtach2QAwLsEwTe2hTO/iqQCem/xBsKqQi90aVexWOe/eGk5yCxSuUyh9gEBmhMX640/8T9L5vt6QbUTp+luLGA75CaUV+tXXnru+ztCVHQxllUE5aaC6sEZPA5M6nw2cZovg1RFpN/nqe3pDoKrEB8tPVja6+G6Tsv9GP36dVI1tPpjwCUYzy2i2hxAcreLQY5QiVolSP2pR9fYFhdwPP5A4IvwXg+nkM6z+8/wra6gSq00LW4Pb8p14CcQ5zY1YiPph+QQEXXsBi3MWDQO1x3BdBwBy9pLSsRylUCzpjU4ehg39wb6xl3ZRYA9yqkXplggzLN0lvEq36xHJB+xFP64KvA1FNp5TejvhSTppJS5v6XG/kgkoc9/U8NOuwJuy0EtuyO/vH2qORgARpanzBCjqcHfaISykkUFg4uZwdY5wZG0NFy4++35xZ+Q5+biuFJ4UYrzGGS0qtRqY7pZBznCHQLPSZsp/RkMwyuqjo0Fm4nIJWvg/h87FGmmsAZsxX8ocrz6blvAsC4Op9UFKIMvoM6sIloImvpYnfLfaptbyXfzF82pXc7eXm0u7xkjACzYtvE0e2+fPTYAIVphQw4dQKbOJIucTProvfggidWfElR
    CLOUDFLARE_EMAIL: AgA+z8uhKTzm7jUDEDSXBP9/SfQRpvR0k09SJlu+WZpgtJVSG8ZHSz0/Xejq0e/8j/MEdtmkp0P44k7ZAchKWCcV4/8vPkcJXZOAlxm6gOQhr6xevvTv4KHV8NslVMBfFE+qfOVgSvijt57rE5inLHrIiaomlsquQft9YzIRMCNke8C8uH0YPrAlgwRKw4iVPf726VR0ZF+xpFlrvp0QFHHNn6l3RqhW2602/Me75h9N2xm266a1eGLwlwkh3vJpxGCgisTSbhjM7D6ijXCA6yLHglD/ww/yQQg+hUL70CteAF94WBinGeWnfhyYTiQwO1NtYILekwOxB2EUcaRRnDwXexgYAxcBPS+yrKdocjcscUrfk3c/Uhcl13Wrrb7nF6S51OQqOWMlIDQJD0ZHXCjxecoW5uOrjncUEoEnRh+GX5RKzhnnlbC6Fz4mUSd88r4V4J/ec5gRGWe8P9XlGyI7iX71nfA3fvk7pufxhzYh8iZ0kosqkzhPGIb8Y2Bs63PxYrp/CCRidIPMp7r4tNeJUcEcCHsR47G31PscoSWGhuXb93cnMzhO+SDrhjXbHHvK7DoqU8VicPM/A9/VUxRIPm3fxQxu0YewfnPTFkqGnGCnsONh5cqmJgGhK71BH6R0iKxWGPPr2adSXKQPgJiHK9WmuJyi5v1lReMZ/wQw64YkJh1AzAIVe0ZvODi4lbEnVJdL0tWU8NedwraaQU7qpA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: external-dns

