apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    CLOUDFLARE_API_KEY: AgB5AnVhB9SDde5z2Xoxcm1ehNjCAYbB6mgYiN49lE5APMZFfLIP+gwMYGEJOPCIqkqGm3uFhrEwStqL31t99fSrJkf1PTDVwI7Ebz0nJBrU25EQxSXp5I/uFOaK8H0BK7pGjt+a33WpoYB36TiAAEWZoV6sbL14cHWs0bDY3o7OkESizzaru15JddCAUcI+qwn3ZIsBuIxSf4QTuxo10iNarBQD1TwXkbOBAZpoNC9mgMyarCl8R01Qg5+7uLn01RBFyu4IIcpDs5+2PhsK/O8UOXkYczN4HKe2JUs0A1arP85qLmyU+WFTex7UyxppcDVpdiYNxXrdNlQw5v1/F764HsJKAq100kF+V/MPK4nAGDoQofrF/8mP/uuu0JW97Oklcg9Gf+IiuVaJ8CiflO42I/AV4dTbcsv3xyNhZIb3Vs1LxD9+CSOS4+0URrws0K4V2v2ein4U727yGWdlY+Fo2oKRcWHn7p3V19A9h+eVKLIs4Iqk+pNZepFL7lAQvARwLVhiEiBPFEjccVEqixM6l7Ph72TfVe20FkxjGcSrOdMB3ljzzI8Vlt8KJLTNTrOviVtfBV1D0xhtq3hLZAXWJNtv8k3wZ9ey1Q/HjyDYBuNauG8J13LYrS/fFZwJZ2QkNtbVhjEmj95h7wwySsadqSCkxWVS/vRiO0ia+8P24KWDWF2OU9eGGuTfxqkZamdmIlBNkp2kqfcD7jCw1bfLx9cvDN/wE73rJdT9IJAy8wS4mHu9
    CLOUDFLARE_EMAIL: AgBrbyZmJsfpJKTq8nxMEUiWqk/jSD+ww0PiegZzqfkl1Uu36IQNtQvz+thou8gPgBI7iq/rE0I94Lu/7bO+tan6V06gsOFHyHspUpU95XL6LwnzYbwpYxg2zj10MJoZsmUQZZw6ERQ9yB//u0cSSvEeD6DgSFT5J3wCmvWMMdTT5227mKX+E0oIzXnYe4k/rUSWpd+JNYHK+eKYKly0QeF4BOkuACHZXGadCkpGjbBzuRxqYk47ogXAmg7+vjjYDSxVDScVfMhOk4BEHuiFKvw6lOlQMdpaCNj045T5LM8ifmTLDtdBLuY4DDoPjG8ozOPLQjTiON7ITPrT4My5Q1/juegwVFYOhXBx8MNPI4e1Ilr/Q1E2+puuK4euLX49Out/GUcoDkYd/WNkmlbij8TaHOtmMlLgViS1ubLYrqlEmS8x9qeWqHj7aEWqdsEEjaONFfq6vLy/2xZVvq8IZGOuNXltnPhUNMtxUOGDptOWuvOWjnTL2y3oQSeEyZU+FE2oB4BDVv2LI9sm/dThKN7IRQ8NOTFAnMU2a74J/eSfR19C9UmJ444S/uJWtyXYKSdgSBYMMfrad0/iGlxq6SNYk/8D/quH2Lji5F4v/kUJLbot8VAxNhIz0HU2jeOvcyc8A8SLxnIU2trPfD20fjaURbJi3P8kOyoTqVgVECBRRa3ECc3BJNFjetO+17of1ZTap9iDTO4EhlP9YqKNazTg1A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: external-dns

