apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fluxcdbot
  namespace: flux-system
spec:
  encryptedData:
    address: AgBkB1M2xs03TtFnq9O92FJzNi39qXwivR9PfE1cQhbidKgKifwhXMKLZTlzeyLRLUwUrfQnNEaxnsmmfkeJEYfB6yh0pHZGLJbyTfrdoLydsXI0L6FSYo7u3VE2Aii+ildq9cO28VatGJ8xDPFvNTzJVQE3cutVWrE4DyCu9WOlStQ0LCJRLruIBOUBgM3wS1jpIj4ZtUguWQtl8iMqEMtkqoS1AGGRQRKkO4TEOUMOk71HI0WC0uwhxtXZwm+68rrF1RPeSeH+5DoEJI4DEpAnwBE1IAjTTn3Xo7l9v8SbSv8LBb8i7U2pz7Im5hAK7RJ1li9dxeWatUnBzqmF0OQxvJRcZ/QAD4eVXHM5+a2UwrcHf433OVDCOQ0mC3pa21eSGCeMFeGvIWcu38DdejnIE/ZaRZeukXoqcd3nqiu7ipvuZK8/5SjJGHCvVvHo2izhX0fEiJI1ENOb564n1TJiGysmkqjotBSUdCi716YbQmSRbU/GYc6mFcfyHwfUtqDPpbGkeRkE3PGROBr4iByaxJVUDDYKtK+v2JSngn+RENF/o7M9nr0Kg63hjS70vuhfjOEX97gO4cj19BogkGNOIZdMs2zVKVYynjpuz1SPtcZLNoEfmtA1TU6nCdN3nHrHtywnlkl06Q6mZ01vlGPYvsRjoPgiW+9NJ+PVuEi+l+bS8i8lg/8qTIeupJgxikKMNJFoG731zQHuwiN1DMaFv0UQH0Iv6MzSSQfidXqSvipTNjbQo0rXfrE3rjPp1isnH8BSKeQCBdhsbz2Nzv2VLp5NLemeANUTlBKi7lJfhY3V5V3N4ISy2L+jT8Lsj8+46p4yIQZY
  template:
    metadata:
      creationTimestamp: null
      name: fluxcdbot
      namespace: flux-system

