apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fluxcdbot
  namespace: flux-system
spec:
  encryptedData:
    address: AgC34a4m/Pi3UHKRxH7pl84UJktmwlkZYP4MSmbrZ/kNf3I8zRTlb3Ls4sxBgHj61r/RQrouxDhwL9P9hHt3VbBYH97+NvW9cTxjq+yXEfjkQnHs9JsNWKiG0l4XmsSj9+zESh2WwdpKV8cvUd0j+H5XxvjEGajdTJLTyMRlNKs+YG8+JHwEkqoXFYfwK5ZXX0Us/innC9kMC4iX8EnI4I65r1WqBC9bhu93Zt5BC5Fyhk4EC+4EgoBYPI2Qpxdvowj9/6sxMc2mygGaLSQGpOOCfwXxwWdQ8OHWrguKtbpDF33/kvQGBbF46Uum8xb6jQJSd3A1uWjhQPU+KDgOXFgScv0BadclKXpZiThRnlWqzrludALFiXJa+pZ95XIwOBbsoEpdqYfWdrNpoB4IFf3uTEhP5TxmGmpaAItjpsgCiM78OktL5ijZWgfIMiIKMiQEIuKKwyDm/XLsP4uwuy3rKuQ+mXxhNtqm/0xCJ6wWKsCqnJ0qyDsyPpnXdIhdu7UozyLoaRWNVO/VbVVLimlAICeSLSXgblRTKfFqk0nRvHk9R2MUzaaUxpvjKgbWQSEqbV1rGHw8W75WBxQV+rA07a/XxsQTCZ5SJSscd20i8z6DI4U/VmSL4xK1WuZX1a+Dip8h4G+0Xe3XS1NPRIXnZvPlqmvR5ITcv+IYstAeKSXkeo0OnlLsrzsp8znJ8RKxe2kA4X4lEkHUHb9T3ssrqfOYmnxURMCn7eevQioLZ3Z4lXeCuHbePcptyoUUkjWrNlvF/VgFdu7UYCreDqEInlDasZ8qiCK2afLxzTnoEFuDrmK4x6/MTAIGtI6HAQBAFuwoIkgY
  template:
    metadata:
      creationTimestamp: null
      name: fluxcdbot
      namespace: flux-system

