apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fluxcdbot
  namespace: flux-system
spec:
  encryptedData:
    address: AgBgIYPK2ytpFfS4rRo9a8acTmsBoj2DnEkQ+k1fUq5RXW2/UU7clLmNEzkZNHG3ZH/sb2PRwWVnF2mGzx+INBMPb58WF3NvxQuts5oSCRuqxSsg96dtgI4ozLSPrBZi7gpbUD0uplxlRT6NikKSrdi0sL1BNCX6k/0Jf4+lzPwWzU1iKfZVG6NbgcfPA48xySg7CDDP9yARVl2/7lKq32RJjvxCxhYPjrCoxZzbXEASdojareBb0g6uOPb09r099bN1zIkvHSdMWJxrTy1HWwOzhOnifa1rrAUj0lFYmuoxwaFzK+CABNk/jC/BI8gOCjCTy4KkqEz0cE69+zU92AH7vbEtItDwFvEKbhSan/gQ4Zpw9mjcc+PZ1JmayY6MJYeOTXMV89lhY1CMElOvgoEmY0VGKwdaouvD4qp7k229B5MZ60vFlBe/ouVS6h0RQMa+YZuN4uVJUnD5oKuaV0WrGaZKbKTO6v/dz0aRoqu3R7Kq/mHPvQgBnKfBF7enKq7MKIujV7mP0tcAcWPC5K6BxlAf9jBK0GaCNE4VX32Nleg4Cb/qYnJEpdqWN2ICJiE59h2oqON2jygSVgiCBboj8ynhGJFvIUHPvzp0BaBlArAbWsPq6VusS1I5io+XbYJrd8RL11Hv0DkwS/aHac69Pz6TFaeVH0GkKtzt7vP+7loOcgNYN5FS+bFp/6JmeG+5zL/Aqcm0dyTfYL7f6/wxRtuecMju5F7t1bbaGCMImHzLgUJaEwrQFHQd4fyEUxu1lS5eV/a7wrnAMUlzgzTHPyt4RqsJoLiXsn0jbZKU2LU9MP0gNFwtwDz83guW0smJn3Evcrvi
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: fluxcdbot
      namespace: flux-system

