apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github
  namespace: flux-system
spec:
  encryptedData:
    token: AgBfZK4jnACg9VR4apvKVavM4GdTFZFOHO+M4snuZ8AVvoxTwbbH6kYTb3UhyZ0AB3szpVyzq7cr/yvEmWVgH0PSPM3QAUlTHZ3RMvqEl+kUgR5lGkgDzEptLvjTs4xFZ+9OnpFAz6V0rnZnY656V9BHRsoUzPAFmmlPRWo3RzeSdM6tllvHWeVdquyw9/M9fX7gyPOP3flVFS7so20SGyI7xaX+bB/2sc1G5u0otsCsDfv//dvehsSE0soHcThg7SAZTVbtx1bMaFt5T0CeuZ4uA5wBiz/UyqDWEzEwJWouQg21MI+eWLpS/WmuLXUr6gu8yrzZsdZWEiAmsfDY+s5VxDF3kIEpVevx5wDyNTfktGlmmhOQWZ9UcySvqWqytfB4hsVOR+z2E/7gXjV4TOaWd0ykRC9PBX2PEJGogkCRKAQCGEQYtv7Oda5/GmJN4fK92flsew0e56wTvzKUjOnnbX9YsP2oQWOzNrD7C3NZ3P0fDsexC+wxkj2wU0rbbrZYFhfw81/jL/JzgohzmftX5wZXTtbR/edcAC/QuDvNQpn7KXziFzPixzft+TLC3oR0yWFveefgVWkkT0Y+4A+3+CZvARVBczbF5uAa9GO5iRGzP1a6lXlVIRgyIsKFn5xRTzmUPH5KSACBYsUUuqOGC2+MWo7Z3I+PZm5Qt+0MzMhFpra/QkdzKe4CwBnHoSu9Xu62Zy6bIc+GngJGTCcOXlgxQYVBqdWrr0FnBajtQdYvBG5CyeK/
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github
      namespace: flux-system

