apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/cert-manager.yaml
- manifests/podmonitor.yaml
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: cert-manager
    namespace: cert-manager
  spec:
    template:
      spec:
        containers:
          - name: cert-manager
            ports:
              - containerPort: 9402
                name: http
                protocol: TCP
