apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/snapcast/snapserver
resources:
- namespace.yaml
- sofa
- sideboard
- camera
- turntable
- shi
components:
- ../../base/librespot
- ../../base/shairport-sync
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Service
  metadata:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: snapserver.k.squat.ai
    name: snapserver
- |-
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: snapserver
  spec:
    template:
      spec:
        nodeName: tiantao
        containers:
        - name: snapserver
          args:
          - --stream.source=meta:///Spotify/Turntable/AirPlay?name=Auto
          - --stream.source=pipe:///var/lib/fifo/librespot?name=Spotify&mode=read&sampleformat=44100:16:2
          - --stream.source=tcp://$(LINE_IN_TURNTABLE_SERVICE_HOST):$(LINE_IN_TURNTABLE_SERVICE_PORT_AUDIO)?name=Turntable&mode=client
          - --stream.source=pipe:///var/lib/fifo/shairport-sync?name=AirPlay&mode=read&sampleformat=44100:16:2
          - --stream.source=tcp://$(LINE_IN_CAMERA_SERVICE_HOST):$(LINE_IN_CAMERA_SERVICE_PORT_AUDIO)?name=Camera&mode=client
- |-
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/auth-signin: https://auth.k.squat.ai/oauth2/start?rd=https%3A%2F%2F$host$escaped_request_uri
      nginx.ingress.kubernetes.io/auth-url: https://auth.k.squat.ai/oauth2/auth
    name: snapserver
patchesJSON6902:
- patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: snapcast.k.squat.ai
    - op: replace
      path: /spec/rules/0/host
      value: snapcast.k.squat.ai
  target:
    kind: Ingress
    name: snapserver
