apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/snapcast/snapserver
resources:
- namespace.yaml
- sofa
- sideboard
- camera
- turntable
components:
- ../../base/librespot
- ../../base/shairport-sync
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: snapserver
  spec:
    template:
      spec:
        nodeName: tiantao
        containers:
        - name: snapserver
          args:
          - --stream.source=meta:///AirPlay/Spotify/Turntable?name=Auto
          - --stream.source=pipe:///var/lib/fifo/shairport-sync?name=AirPlay&mode=read&sampleformat=44100:16:2
          - --stream.source=pipe:///var/lib/fifo/librespot?name=Spotify&mode=read&sampleformat=44100:16:2
          - --stream.source=tcp://$(LINE_IN_TURNTABLE_SERVICE_HOST):$(LINE_IN_TURNTABLE_SERVICE_PORT_AUDIO)?name=Turntable&mode=client
          - --stream.source=tcp://$(LINE_IN_CAMERA_SERVICE_HOST):$(LINE_IN_CAMERA_SERVICE_PORT_AUDIO)?name=Camera&mode=client
- |-
  apiVersion: v1
  kind: Service
  metadata:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: snapcast.k.squat.ai
    name: snapserver
