apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/snapcast
components:
- ../../base/librespot
- ../../base/shairport-sync
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: snapserver
  spec:
    template:
      spec:
        nodeName: tiantao
        containers:
        - name: snapserver
          args:
          - --stream.source=pipe:///var/lib/fifo/librespot?name=Spotify&mode=read&sampleformat=44100:16:2
          - --stream.source=pipe:///var/lib/fifo/shairport-sync?name=AirPlay&mode=read&sampleformat=44100:16:2
          - --stream.source=meta:///AirPlay/Spotify?name=Auto
- |-
  apiVersion: v1
  kind: Service
  metadata:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: snapcast.k.squat.ai
    name: snapserver
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: snapclient
  spec:
    template:
      spec:
        containers:
        - name: snapclient
          resources:
            limits:
              squat.ai/audio: 1
        nodeName: tiantao
