apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fluxcdbot
  namespace: flux-system
spec:
  encryptedData:
    address: AgBSqq/OqYk0AKD085qKYtFXg0PQbJzRcuwq/duCej2irV6P6jhh6UoBlMgmDJXkXZXBg2/QBRe8BwsbKkpOhDWRQfyQMU4tCEjhfVFKlk/jA5PRgLj4kmIUMcsyPfj9HHQz3FgKz8pVF1invzoql1lAqJHyXaxFTgH7NrMuVyiF8w3oXnFnJrvXUaiXIpsnREnUvtKojnK/WrVB8ST7Mvdngtxaa3GJ7kZrjQPV/cyHJYe9n5UZGofa4csDmzTiqXapsQjTu4M+q3h3TizQb4jD8llWrYdAVIcloN3o32lnyILQWUUfokeW4bcGRpZ59PpaPjeTxXdjtg0kzPjfdk/uBhbirkUQsrgpNL5Xx3Mi2wDis3Ikn/CFW+ewrJd4ZM8rzGhMSxMoFntWn+YwjUUxn6R2b1MrauWVv8ZCtr8361iBmHsi6wVX9GnaLYieBq6D99zPjMb7PCx3uu3ylaH7LBQkSZwQmEeUcE79+VzN97oX7MrBNKL8WCA4K0ciYGRHCAwMPiydl3THzeSyB+4WZ8iEs4pKe80DcI4LfG47CGq/wINM06/goWJ37ajk2DwCmfe6Cs7l/VuWrOGRgf3dDf/I6Zmj0B4EmQgqDpfGiKxO3QmNTBUvXDPrafq1FGzYafCRx6bTB/kes/UR/T8gvP8OkXGxnHhcv7SLCAeR01SlqxhfkvWzDUN9kVCIidoMvEh1GZeEHakGeCCAiU6std107MxXcWSkDEPGz/KTA4RV31JNLxbhM34Zvr0qyAB2N/G5b9U8KP9mMOtm3/LmuplCDrEZYbwe53yuTOu/CYfCkLnWeDa6lly8sZen5gMCpLCBHFog8O4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: fluxcdbot
      namespace: flux-system

