apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fluxcdbot
  namespace: flux-system
spec:
  encryptedData:
    address: AgBRPkC+ZmUl/4alJiu5sWo9SeSJzUxJxgBkdCnBGTRG5MioPPlqrc81Rg4AumkW7BjljeLnsx1jlH+t8Yedl0j1ktyqOgUt6qIZQJPrDUWHzNlUAsY+baxUPztUUYjqQjGwNCXOLeS1FVqRRbNe0nv7VYkkWUobhNGTKJXDu1Vzi3wYfWJQk5Z5LoanQ1RN9/7xoRO+9RoZB1YHSqWBO+ElHiEomxhI4nQpYor4epRL83zf239+tckiQa+tsoQKT7f6t/CbYvWheLiuAdhFLzyGlzvVCqvEEX16ZRi+5gCR79DqJ4K27H6Up/mTvc2fVm45s0xQICPB2xmgrinMSPPnmfpCO9v6gtQkZE2IHD1eNHzTo5p5ydqgRfd/xvo6+qw0YCZRh2kInduvDNqJppknYCaVvmODhKlZeLx7p1jwYc5WosADXFGB0eWReDyQI4auL3koH2qGhcqEX6gSfXmzhT/Ru0BPt/lRGYF1ko4H1EmrmmhUR+SPiSjXZvGanSyBJKckyCH3G+LrNcAmifrq0Q3fD1bJMuwU/oBud4qWJ/fV4weKiGoL5XgHJZnB5nxS2WV2OVDuAfM4mWTpHDfekb+LTIZ+cOVCHScQ6aCTwJNyyZcAJT8u5jhlaTRqIcETwAaRrVT7rBBcsPofeNo5g/cAKaWKH7BjZJM6fxCCevG918KOluz9QyuxvC8iMaffIIs9AA8ed3rgdEh6ImvUTIsE74vgsEue3T97cAz4aTyveo6ddVLkcLw+AUk9eNBhtz/2yyR8w56MyL7VLd9NMYwWOjHgGm3IN3k6QGxWGVAUPvq3IZj5N80iX5YX/8co8qizmdhR
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: fluxcdbot
      namespace: flux-system

