apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fluxcdbot
  namespace: flux-system
spec:
  encryptedData:
    address: AgAYKqblLT2+NX6r8xDIK1D7F20k8cwMQYkmJnZ8cmUd2UQanKrCEiqDjOBE+UGEfy+fAxGDfWhu35Ap+21Td+I888q9sdYY1QGVkOxZx4OwgtiUeVfj16w258I2sRwn+9OpgfhC2lzF3pRC2PQzTlJe4SmHUDB/cCvq+uT+jWV1gtwkgf2zKsOaWjYs8tf8DhzSG/lIZ82td1Ho+htkB46ExNlkTNTbuRMrOp99p4fsd1aaKylM+fI1zqndLaW9uXs1+qKGAEx48eBeQkB18P214e+gnG+hL00Gn1G8R1kjijiX9ZOzD5hG0napiziVtNyxxVtX3mHmjFWDMBMkKnD7lvqq8dlee4935ttjwem2Rccfn3zT7zzNGVDPzCZ6pwHwn+Uqer1vE3sMGzSiPqDZ5/CrVLPMsncnDj0rYAXw4j3QlQx4GoLfFqDR6fBM33KZXsekbECncb4XtSx7cDPLvpeibrmisBDrtSIoYs0Q8I0cEM9v7OUKUk4OmkMBh9o9mjWv5KNe9fe58WIrZlQQNrdMNTQ922YmYiaIhoAz6KKxWr2Z2KdlCKKfT1rjrUlLSkx9Uv2Du+T18ENNJs1FBITs9I5OU+ycJmij0awpsorMzH/WGwcYrTxqSghLDGjLnviA6tNAcIhveAz9hKujD3GtOZeiZD5Y9ShxuhJRD05Lmq9HVXBGEOxad2H4azy97Hryt89k4GCQy8c8bgufnt4kX73RJwuAXnTTbmHp5mkmOc3J/jchFJzW/BSVqicfOcvCDbXL/Kypx9R690QtCWQBu6fMi2j03+7g79rWNC9k/JsF0XgKvGuJkQBz7AP8bUb4rBw0
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: fluxcdbot
      namespace: flux-system

