apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github
  namespace: flux-system
spec:
  encryptedData:
    token: AgAdFUYuLV09qy8nBjrkRf0yJz6X9CA5ETj/KAPG9kRl6q/XOmncvWYXeESaW+4CzBTmqBDS216DuE/vH3TB+TGugJF/P9PpNUgIcmrVpRlYJCDqW7tKkq2X9vq7bOKbZfFosWr0kmgvrWV1H6MYhdR7+mpj4YGbZr1KUrcVMglCR0WRXT/rcnlcboKXxXQfJIzxxQHknAryOrrTFPhoj4fwtzBiUyFyCa8q7x0nxgkddapfOC2G5yugyvi8ybbKayat7Dd7IvuugAr5gjYsoJbBM+PvgSsLZcUzpKZ2MPWUAAVZPiTlBmmJV0dn6345nX9D15QAK8I45j1D97iFEsnn8WaKyCNM4smJPc8cIY/SEm18Y1ZWr1raOc9cBtYhdNhh3mHQ7SgvBHJqbc0XG8l907igzRUT5Q7P+PJXds9Y6Wunf1H/8Pf6Qpguis2dx0mtChC+A073CZQTdy2UEcxmL1J2ybZSc9awBdqrXqKMfukNyGJkzW8xYIBZfgmTeG3NA+BNzINk0FXEoAvWvdw4VdwVkBUe52ctuW7HmEBKHPxGXWBqwCb4SDKFfTcWJWrSzT8mAy3UtuaPFHK9ygksHqt13aIBoIW/1rvu/SHxVWavNYTlQA1PIPCHm4ch/MimQKjKB4l7/SyS1go8lrVCNjDexQqS8iXfkV9QeEEsvUELMLB/SvrNCtU8Y/qkJb+qxQ39dnBTtN2D+x77jo7U1IPhgQ+vPgxYP6YDXST1kHDOmaQDKsio
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github
      namespace: flux-system

