apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github
  namespace: flux-system
spec:
  encryptedData:
    token: AgCco/Y6u5ZM14tyJxCimjpOplNYAsDJ4z31yVt+r1SjL0UpIl//7E0iJQb8uIBBYDKeJXUN6e5jOHUCTjDJkLeipjgoUcW5G0baGFoH58REMfZ1cFTRv0qVdjniUWVKf7IozjvAn3bmqETdkpDZZW3J7/eU5GLlUIuc/r9RIfK7x7Oh8V+JS0lcoV2IgSj5+fEKDj/Sl6tZA3BptWv2BMQtJXEqtOuSH7aByasdyObSGUfNl4eqUnaowJLrcBqZtS0yxbDLe5fXSk65oHmTkVINZOcrWuN2iDZQXkEZAfxzRVMFE2e+9BXfY4ZHg0mxi02oB+r4fWZz3xadX5RS6z5dSoktVx3tCryL5Nx41gckFZpecyfrInqgqJTitNt4+RLg7Pbmy6qGjD7mtRa1Zj/obPlArrq1R9p2Uq7fV3pI1F4zInbJD6u4b2qsT/Jmsx8MStGs8kZpSMgEtBt+xcZc6BSxPpaeOl9DOI93AIDPeqC4J/dE1aIPQPGUvHn3CNVdvUJmEzZUKKwhUbOEznYjT9QyTHBCA7gqLeO8tO4/GZ/f+PsaGA/Ock2ui5LGAxUhlExnw+aiZA72M/JLNGSRZr5hEJcv8mxYusw2t6zrWYqvKAfruVH4wTB9zAQ1qycRida/zv1rIV+ybKMUJ9UgdBpjO9DvLeULJBiNVS6QWkaH5ceBhHy4661CAi9D4684uUfgis0FMOCcLFvM3AShLVXYlEUjlppI+1L5b1JIEJdpq0If9K6l
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github
      namespace: flux-system

