apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- github-secret-sealed.yaml
- pgp-public-keys-secret-sealed.yaml
- fluxcdbot-secret-sealed.yaml
- notification.yaml
patchesStrategicMerge:
- patch.yaml
