apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-main
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgCgwYLf9uX4eEWAJl+gomOKeWyeareG9Xay6J5cWvVA3n/HcDpxzHUA5LfvCsbDYIpNrZPQgnLhiOV72wX/nSimnF7zkIr2oJBE1XwAN2/HbyLz9JerX/62dsTOnH1ZfDkJ3HQNjQ2rKnvybXDMde1plfHPveFuxw0nv+qzuBv3qYP5HkH8uqkR71X1LiDoMQXDUC+EZz9d79eVHeOy1brEKkWkcROpqMMwbO8K/bhgsOkHEByHXD1ZboQuE9IRVd7srJDM7hmMbjQD5PX8kb9K6n34pZmgyKii2N4Swpf2BCsduZrOt3vDB5P1mvFyAsGTYRJZkfjzAMzKfiQlL20A+JtNznYP+h4kfoz9mve1FfxCT0ynfjdunsWoub2JFbkywMn0pjJM0riyBqfubMqT1pyCbX8DDF3mpvNq64t0T8/OD1xMXpQ8Gfv6v8MosJUz8em5yoVb6VYIyfE8gLhUAEy6wdnqRKFzVGBvolVMwsPllwcVu91J+77BM0foBHYAc5ZwZtc/jrl72cQsXARW6YqqAERgYqx1YMonYYjfbaGp4cd6AJmjrzWnxRFRcvBWsfg2bJuzfr8s4J0GStG7+W2N/p53J+hV9eA7jm6x4eIPh1Wk1p2ZUmNVmsUL1KptbuaheGgxROUlUCQ4dllvnXBv9k++RQZUyVQigdxOMvYDaY2w+dS7LJv/gektPnV8GCavaV+fPoaO60TQrexFxW7nCrfc6C+bCGNkd7SwAKMbORb/Np3kz0yXPBghcUVejvEg93fqKYqnNTHeur8CTH91FWr9I6ObtGR/QgPrKUrvRxjVeibpe4L8Fr65K9ZWL3jX4ZPjc2puMCdurKSSG2WoWyb6vq12e3pnTkxyj7+C5s6HcPgdjCuAn7jgzQpJYdtImGH4sJOHLRt34UAkDxnFMLXS1oO4oeV1ODGW/L0kWczMuTwcEl2E8CUS8Ig98Yf3xx6X/uLt8zgjAXEhvuN4b4zkPM9avQxROs06IGmxqO1R/H2tkhJXb2nuFIxBekxao+eI8CpNgHE/leT4I355aLbo2NN/3pix+n4c/hIW/hTlnA1UTyXrX6rShs3KzrGm7WRQYOydP02ldU69hxYK6wEOBdHwnnnKiytOhnsEbN/sJTtSvXZxWyCUvw5fJ+PPiiVZ0dd8fdDlgtwVXW+UsLINSghPVQN8woWgGyphN3tbaCFHWZqr4Gui6cNioEeY3s+Z2yBzfkpeyPm8ZdQMa6d5QmkXcstzMboKZR5ZXr64W+8uMuLKuibxQs+ZwDd6KgghU27vK9abzgT3n7STJEwpS+xXApFHYqju4Z3jseqH9ZGb7RBc+htOcGlHjGyfdfcTMs4N/7ColFEV88gflC5WRTpEFy+wlQ3Tv24f49LGEwu3dEXqceliDcU+nXMjNZPcwEcIeCGrBUKYBeTCHJBYPFgPNEGr2XRrZuCfuvJMgUiwNmqvVM9cabaYjb7tLAD/uxe1k7anv30LN745EAD1qnCkKgGJHkPvHPbTS3MHi2ZRPHDqT14G0jwDf6Co3YJJkUBh3+n5itqL4+f65U6kmr+zZ7Nt0AcW/6PD+NrRA6iUyU67dGw1+BWXDHAHu5H9zNxQVEotmA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        alertmanager: main
        app.kubernetes.io/component: alert-router
        app.kubernetes.io/name: alertmanager
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 0.22.2
      name: alertmanager-main
      namespace: monitoring
    type: Opaque

