apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oauth2-proxy
commonLabels:
  app.kubernetes.io/name: oauth2-proxy
  app.kubernetes.io/component: proxy
resources:
- namespace.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/ingress.yaml
