apiVersion: v1
kind: Namespace
metadata:
  name: binomial
---
apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: food
  namespace: binomial
spec:
  size: 1
  pod:
    enableMetrics: true
    metricsImage: "synadia/prometheus-nats-exporter"
    metricsImageTag: "0.6.2"
    enableConfigReload: true
    reloaderImage: natsio/nats-server-config-reloader
    reloaderImageTag: "0.6.1"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nats-cluster
  namespace: binomial
  labels:
    app.kubernetes.io/name: nats
    nats_cluster: food
spec:
  selector:
    matchLabels:
      app: nats
      nats_cluster: food
  endpoints:
  - port: metrics
---
apiVersion: streaming.nats.io/v1alpha1
kind: NatsStreamingCluster
metadata:
  name: food-stan
  namespace: binomial
spec:
  size: 3
  natsSvc: food
  config: {}
  configFile: "/etc/stan/config/stan.conf"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stan
        app.kubernetes.io/instance: food
    spec:
      containers:
      - ports:
        - containerPort: 8222
      containers:
        - name: nats-streaming
          volumeMounts:
          - mountPath: /etc/stan/config
            name: stan
            readOnly: true
            items:
            - key: stan.conf
              path: stan.conf
      volumes:
      - name: stan
        configMap:
          name: food-stan
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: food-stan
  namespace: binomial
data:
  stan.conf: |
    http: 0.0.0.0:8222
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: stan
    app.kubernetes.io/instance: food
  name: food-stan
  namespace: binomial
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8222
  selector:
    app: nats-streaming
    stan_cluster: food-stan
