apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: food-crawler
    app.kubernetes.io/instance: bbcgoodfood
  name: food-crawler-bbcgoodfood
  namespace: binomial
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: food-crawler
        app.kubernetes.io/instance: bbcgoodfood
    spec:
      containers:
      - name: crawler
        image: binomiallabs/food
        args:
        - --log-level=info
        - crawl
        - bbcgoodfood
        - --url=nats://food.binomial.svc.cluster.local:4222
        - --client-id=$(POD_NAME)
        - --cluster-id=food-stan
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: food-crawler
    app.kubernetes.io/instance: nytimes
  name: food-crawler-nytimes
  namespace: binomial
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: food-crawler
        app.kubernetes.io/instance: nytimes
    spec:
      containers:
      - name: crawler
        image: binomiallabs/food
        args:
        - --log-level=info
        - crawl
        - nytimes
        - --url=nats://food.binomial.svc.cluster.local:4222
        - --client-id=$(POD_NAME)
        - --cluster-id=food-stan
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: food-crawler
    app.kubernetes.io/instance: epicurious
  name: food-crawler-epicurious
  namespace: binomial
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: food-crawler
        app.kubernetes.io/instance: epicurious
    spec:
      containers:
      - name: crawler
        image: binomiallabs/food
        args:
        - --log-level=info
        - crawl
        - epicurious
        - --url=nats://food.binomial.svc.cluster.local:4222
        - --client-id=$(POD_NAME)
        - --cluster-id=food-stan
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      restartPolicy: OnFailure
