apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fluxcdbot
  namespace: default
spec:
  encryptedData:
    token: AgAb97psSjdLU60gfVZ/oDH51ufGp+2tuyZatWZzx0Dd8UGrSgQMy8B97mw9y1v6Fj8VNHQEQD3tHDfSsTMiYEoe4za7TRyNMnuCXQGAPscwoCcOoKBfSxRXj6izCklFHPwm3X790WJ5zoYcDGK+y5G2XzHjoCfPi9swJ4yAIkhcNgd6iNoQg6Q3sPROv+UaMhNbnXaL914CVmtGXiugojQuJmAiDmiTmzU7eIDlpnefpJ8i9zAekRK4ZObqoHraFh/L5Xi5Lpc8Isq1j1zXTAscggGwJGEw8yaVGI2VoMYr/WHZhbpGdR4VXaLD3vhh0AenPkk/TmyVNbhRR1RRyUR1Fo0KmLq/vYWZULZrYxCK7Vxbm7fRljB5Jusa8WmXSIX2YdUf7cQHIzmnbFHqWmGCLQaVLjWk9U2+5Hkxab7nrlf9HyyWYiXMHN472qoOcXr0WRo1VY68k4Ut+3QtScLjK0FsC0v+Cm9vN5fBgfcErgwfU5RlxKD3mQChcwlJ7UYg50X+of3SYylEe4fThOXeSC/d49eERagbGnPRwv507ADc1neuZxLohNnNay694aTT5UnXpXHhLM34fkgpGMqnyK7o3i1DIeni5yB6+m29J0qrbQcA9dAdb2PcLLZWmCiIOsO5JIGNrJvVdeG64FuO+ptB7ofpcNwJjH66k+TYjxhZYeUe5zNDORjb+pYf+IdZ1/gscpKy7zRUzhKacqfu5nPXPnqR3lQM2/ZZfLleCZ9Sa4VkWzxDAX3K5ILv
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: fluxcdbot
      namespace: default

