apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fluxcdbot
  namespace: default
spec:
  encryptedData:
    token: AgCis9bX9P7qZoEwUAIfH7+bwRST2dMCRzdkZ41RFs/RaG9KYUX7TGxYi6Fh9SEicY1k1gJhYC2+BsBMkivc/tGRo5LIjYoF16uIJcxjuDlRTjBPb3VkEm1KrUv5tUHNKiep2zPPUwTDdH4EUW95MidyA2YdPoyOiLIoLd0dPhQQIrTyvW9IsDF6mZL3h9UW1tbVywmxDlYkVWYoHqUwjhgTzDCfxnzai8kK3LGM3Ub7K+rcV06dLB8oB5tzx56aj6a08WoJyvvfGoxwcMsZ9TR3saMUsdnQjNiW0N/TX4vkRH4iWGmrJKsTuPOOpER8GsXv2LS2ygR7dw4Yb1xVMYRdSvEwvo/z4w7kM8qc0aDp3LtQUvAYk3DJFV2ZtX5Lzi3e5Bcu64CqlMquBtEEhWt+lnOFHlH3lYKif3GEF0kJeQy8z7+CTMIy5iG6cfi9zPJ2ji7X5aVVySE9/DPqc0aU3FljXvMybfkQfzPkMa9DnrfK5S5UmKdLeVfF+nUSNgVyo82CkHS+I/fJ6F6pSjIo9+gXjA6HfAX7H5vOENBdYUBF2hxSv8aha4KScnRlQsyVv9ALdv5xFKQpcz60ULHDSSz/alXAldUl1BxmqVm3M/qqhABn6LGjbJ5pOpx3a0Zu4uuDfbUBmrJe0Jx6DSdLsSQr8FYKduRAWdWMqMG2seg93YpIPIsrFMV6KzBuRNBwMscx57CZfKyrrza0zxd6N81vqnv74oEJlYpa7gZnkSxltg7kLruwsqI75aXO
  template:
    metadata:
      creationTimestamp: null
      name: fluxcdbot
      namespace: default

