apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: turntable
bases:
- ../../../base/snapcast/line-in
nameSuffix: -turntable
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: line-in
  spec:
    template:
      spec:
        containers:
        - name: line-in
          resources:
            limits:
              squat.ai/capture: 1
        nodeName: lu
