apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../base/snapcast/snapclient
commonLabels:
  app.kubernetes.io/instance: sideboard
patchesJSON6902:
- target:
    kind: Deployment
    name: snapclient
  patch: |-
    - op: replace
      path: /metadata/name
      value: snapclient-sideboard
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: snapclient
  spec:
    template:
      spec:
        hostname: sideboard
        containers:
        - name: snapclient
          resources:
            limits:
              squat.ai/audio: 1
        nodeName: lu
