apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kilo-wg-gen-web
  name: kilo-wg-gen-web-headless
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
  selector:
    app.kubernetes.io/name: kilo-wg-gen-web
