apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: default
spec:
  encryptedData:
    CLOUDFLARE_API_KEY: AgAVfDHY3rvbMK7G3GIXm0E1cDc5it5D4nowNWdyLDeTat6fyZ/6BVCQbI18ArAka8Xh7ft8u8PKFK1150Lmb+ShxfmWMu5ECHsCYFsOsl5orqB9GEfPLzAgLTKhZB3Pdy1GPY1c0PN8ywGqKja7bBSD/IxK+0pGvfMDg5eEPWttiHPxJegnrJ+PFQ8euQtIqm2LQcUev/80C3tR2a9Ya5rxlkZ9k/TnjrU9fhnr4YRLu0YqKmbEIAN5iQtzBBakmzBDM7VL8Qzw/MUNWsJDd1cHXNdNJPL581g+VUEosqHXGWt7sE8+PfQ3XTdqBJjd//geQvBHGkgug3EcZ57tF50e5ENlswbkiI03YhwSobJe0Y5/GE2qzk5Eh4vhX0dbuMJB3rUjDW0Cg2p8AvGkctYLznmr1c5hRgLyPuTvKOZd+2xovnok/GgKgrC89brBWknCeXOTvfptEClk4gYVx2q24fdXu4JFTEbwteMQzFIRRyKo311mb7Wj86hHySFT84WTFbkMvXGx9RfqUy8Zt3B+EjeIAmNvndODwWmZaEW6qu1XPvGaMLKRR7UkKY3sYY02hImYyI5h8fFN1RGCpVvC2kXqBnZpMn77PX2XSqrx6vsw8eqK3om5cd1Ua1FvL5OEjmKqUQyG+2EeJqgqK14R1MmBJ7U7Gg4VIaOz3XB9ZjHQllLab0DjTa5gwj2hhMqD0M1ezDOdnpSOT0po+qr/bKxo5AZIplZ0FQOey65/OfM+22+Q
    CLOUDFLARE_EMAIL: AgAdKoavQCf9lYgSZAFqQSLzjrPqA2NLEO1pCXFqL3sWKvmb6HjmgSCiX1Jwzea2sGcVB3u0mlp85lhO8igo6W4V74fa5D9v3ZVWpv3bH+mb0u5PJtI+Wt5+qZBCj5KYW/O9WhJrAx5u+nQOep7kxxrAvn/9ryqDGY2h8ghmfMt6TTB1F6drF2qTzBgLciC+C/6/P2Zx93MlwyQbyYd4IaPlpCjQ4GODc4vnZV9KMy10cg688xwjlkjhNasyePsD+3d8KkSmHFlYjt/n4anAroOw8mOTMCG8Kq9qRZurtuT+gD8ukZXUN5497ZkLSVJwCW0FOaVCzlLYxnXdm6xlEcO9pBoKUCdlD5OQjVVg9ubHH0QNmfWhmMHYDoS/rq2uEm+Ee7UNITRebL+3JDOfhdz1JZcl7a0M5aGCpORY1L6b+1DqRzwWxphDVIpWLltOEJadLCNxOFigZd2wDywuegom1cPyzP9lX+9NzLkbZ+1wM0jCzMP8x8jCQMfsOixt8FEvNUJM7DrV05o6rpLHq+1hw97lNtSJ1rm1yLP8itrIlaSuBNaJlrreiBy0uVYQgectmPuKqmUGycGxbGSowg6TexBi/6j/dn5sNwMgnBMhC4GGsx07PqouJEsgMMjI3HfyDpWe2R8H9nPNXfse+2a+pWwtEom/C0GM22LN7ysr4qCY29MdCDcxD895gB1eGphwk8gK+5wCDczum3OzhtA7tQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: default

