apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: default
spec:
  encryptedData:
    CLOUDFLARE_API_KEY: AgC0R6mGF5ihMR4a0yHpwmdoAa0LUj6bi+QJhVsf6mJAhP8KZ1Z495xh6GC/K9yrDEA7R3LFWLyp5bfny1uPMeZze09xdHlpWBRvEeVf3pSeTUAEVnk8OrnxXeY6VenCsSHSMvVdR9NrYOutAKamuO/0SAIherXZME7LoslwnncYLVlsCTX0VO4opNMumsbWMDV72mMkuXrboLXThVIgU2PLf7hxPSQVwMiWHL9BzpvEVNsFfhfsWPspRYK/Sja5udbWUq8KVH6LHd8vuZ3kAOZUoe9UUhNlnCbdj+pKyZaQTmQ1NqDDTkLdx+pEe+BIp6A+1rl8cb/aFssKSIBWT31a0W2n86pIoNiVFnYh5nVZ8cLy//jIIlKmAS6/kLcO/g+K+AXofSGNE/bz2hEXjBU5idKWKTB8ubCMX92p/oy/oXAaAnc1n+rJ8rZkeYBXVhkp7Wxnj6RQmzT2A4wLdgfiSH/Pm1pIK2ji+I4fmTlJdPFGettESpMNnVvu5pvVBbKhsFDhTGStXB9ZOq5FIMIorWr1CEYyggeu1HkPaEFQqCTZOyJ69sUf+exy8dQ3/3iTAgkEnvuIbwpu0J4OtmogWv5QVBw8D6C0/H52R7TLm/kWF71lExEfxkCY19kvc+E2Jipu1JldiHavByXCpV/Iq9BZlUwCTwc8ksgstacO8bfqaSZfrBL3U6JqUIAYbexNVBJydeZ4665rvvOvC5MHxQdDXM8XtxnbXww6P9cqhOAOh+mA
    CLOUDFLARE_EMAIL: AgApFrB7bKzPu+Av7QEDbCa0xFSTzqzDzh4hGLs9f0+EOs9NZm0rabqxxMq9nbye9RsT/GxgBFe6G3PYniqKmkJ4s5dhvSNsOoc8/HZF8FzIqgyCgtTIltMELKY0M4tIHIQG4KX/baF8q42xRLjiJMWRe6vnGE4cWOCwfERUzPqD9IyBm0va3vDmViTvi7PMmemLce8pucW2hDmDWUEUp4XbWcm+WGXh5SCjEfs9gGCvKJYKc+zdGae3Jazn2L/foOreAzdEeRwi5adsgTE2KpdvSqjlzm1Yr46Hrvb5VVF/uJif6wpNHbntz7WIE6kiMdt+pQlPC/sn92B2rMsX+kmk9XIZZis4gDaRWMAsTDaljZMe//gOa8f7W+hwPbSu6ioF7qzCE1Mi1tmvb2XHPQFYCeU6gHGtR42RIU64QPLbo0BkAZqklbKONxB0HV7hIdylg1BSfWx07rJ6hpiJef2E0XKOBwzclw7aEZDFgZu+sif7oJwkqfuHrrKewI0D0p1w49Flv5Qigr7Jfncs9eu/m3TjvQv1l3gqWGime3ZL0nixocgCWtXafC0MNFSSuhfS/cy+c4D3e0zib2xCsEJ2Hk4mivZ2MdOo8buTQ4QIsdI94Xbkzqj9j8CWdbBDPyfFJucsw1pct0Z/axWbJVd885Z6MeI8Ewi//z1rHEXA9VzMNT11wG+mhQOUOTxmEq4nER+NFwkF1wHzwuZ6qYQ9qA==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: default

