apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: adjacency
  name: adjacency
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: adjacency
  ports:
    - name: http
      protocol: TCP
      port: 8080
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: adjacency
  name: adjacency
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: adjacency
  template:
    metadata:
      labels:
        app.kubernetes.io/name: adjacency
    spec:
      containers:
      - name: adjacency
        image: heptoprint/adjacency
        args:
        - --listen-address=:8080
        - --srv=_http._tcp.adjacency
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: adjacency-curl
  name: adjacency-curl
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: adjacency-curl
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: adjacency-curl
        spec:
          containers:
          - name: curl
            image: curlimages/curl
            command:
            - /bin/sh
            - -c
            - json="$(curl --fail --silent --show-error adjacency.default.svc.cluster.local:8080?json=true)" && [ $(echo "$json" | grep -o '],"ok":\w*false' | wc -l) -eq 0 ] && curl --fail https://hc-ping.com/5c31fdad-ede4-4e9c-9a36-788ffe29f78c
          restartPolicy: Never
