apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  labels:
    app.kubernetes.io/name: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
  labels:
    app.kubernetes.io/name: external-dns
rules:
- apiGroups: [""]
  resources: ["endpoints","services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"] 
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns
  labels:
    app.kubernetes.io/name: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  labels:
    app.kubernetes.io/name: external-dns
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: squat/external-dns-arm64:v0.7.1-64-g11ab08b6-dirty
        args:
        - --source=service
        - --domain-filter=squat.ai
        - --provider=cloudflare
        - --publish-internal-services
        - --log-level=info
        env:
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: external-dns
              key: CLOUDFLARE_API_KEY
        - name: CF_API_EMAIL
          valueFrom:
            secretKeyRef:
              name: external-dns
              key: CLOUDFLARE_EMAIL
        resources:
          limits:
            cpu: 250m
---
apiVersion: v1
kind: Secret
metadata:
  name: external-dns
stringData:
  CLOUDFLARE_API_KEY:
  CLOUDFLARE_EMAIL:
