apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
bases:
- ../../base/ingress-nginx
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: ingress-nginx-controller
    namespace: ingress-nginx
  spec:
    template:
      spec:
        nodeSelector:
          topology.kubernetes.io/region: hetzner-workers
