apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: snapserver
  spec:
    template:
      spec:
        hostNetwork: true
        initContainers:
        - name: librespot-fifo
          image: alpine:3.13.6
          command:
          - /usr/bin/mkfifo
          args:
          - /var/lib/fifo/librespot
          volumeMounts:
          - name: fifo
            mountPath: /var/lib/fifo
        containers:
        - name: librespot
          image: mazzolino/librespot-snapserver:0.25.0
          command:
          - /usr/local/bin/librespot
          args:
          - --backend=pipe
          - --device=/var/lib/fifo/librespot
          volumeMounts:
          - name: fifo
            mountPath: /var/lib/fifo
