apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fluxcdbot
  namespace: default
spec:
  encryptedData:
    token: AgASRtYs6HTywbt+P0hbwEAye7JdRVoQpLyZrfRequewmk5Vt56LslhT/RBK0j5fIpCidtXNzVl6930L8zt8p55QN18gDT4w5xCpVooWJwBJekHM7cEUQMJII77r8hW1Krj/vjlON7XVS4j8Pw0BOiNSkD8yInlcTMOG8mlh7jAWRR8F7BM+9rb6bNSecJOA9DnKMnUJVBEQxS/lUKdrU+RBfsdSikOhvKgjJN3kn5ELHYUNmOAeNKB85JWCMmOnHzUPXYKbifSOErdY09ofiV77mBJYPKIQtNkWY6nT2w4HuKX7X4JSW6Q+ZrLwMBHjs1NLFDP5rTnRiTgYvDKEUTW+31VlTFg812Md8PomBj1w9N6VFr39JZPiex3+fB2ATnEXdHkeinSttkAFZEI3om/LX4RvpIPs0RwOQE6d0Vv3InvD34Pgb9y58xfMk580iivS93NfKQ8lPFVceagQkb+QmqgqaKZxtScXqRqfOps7Ax/U7hj+jfR9gj40r4YI0NNNBHCBGf/rNXMX+oDPy6AlxI/REvJbahbNjEMUCnDdtjLO31zPm0rhBNQpoqvqyNuHyaTlOlY3C9bCmZnWNGdLWsID5pH97XtwVNC2p9hWyqDsJ4g8kpY5pDf65qlZuv1Y0FL3yY8+N+Uoy4MQYqFu4AcD/Sv0FlCF1Od0TLiBClCJ8HM4G+NJY8Kt7jCptkjKsQhRRaLK2+ZhXa8NMWReppQMAgWBuhaed6BUxZ+c16GaPt4H+dMXfu2pw5br
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: fluxcdbot
      namespace: default

