apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fluxcdbot
  namespace: default
spec:
  encryptedData:
    token: AgCJ0wc1XvP1IrPxHhY2mjMvnWI8aHYNqlIf2EqUQOpMh5EZ22HjX369kLvWku/mbjWKMrSzni9Hc4lZBWdXpneQKiStOIyBsmaJHWeBLcTaNUxotwoAnWW/E0qTeatP9hSrgH7lCj4MKgk2I+3aGDyhTSq6lZkFL6SSHFCa/LO4HiLTuDUXUGE/nkyjVovAcNuC34FxvSCQNicsqnATPgkv7F4/YnFc0nZ9t64YLlvps+TJ7PfLkCRt4R4Ps0VjLCU/7+/D7o/DllhYgJSd0BWlI42DYQOFzObDK6Jx80dxwzb0rACyRH1jeZDfsUeN93DPto+Z0oSlsx+5/vzOmRrQakp2sGOWhVLIH6XmhvWNRry02z96xkN5uF8hQf8YLFMgRS27jReBOLrTf3EtgHJwPqINO6lDiLiG9BcQkGRpytqHOrx8iLeW40wBGKqgEc2aOFrbvW42nz8SKtN8LHk9OHIYPWC5y1RQ+exTiUil11fovpCZI3hWLbeCSP+FSrEImVmfqTO9VFSTLYAjiYBUCCCe1PFffqXnihKZ8bA8V5cwc2ZLh6tq06rtSmy+h6U/L1dCVFGZejDOcEKEwaz3oCvzM0ABX9Vr22giTzMz2wRsy7SNJxCifNGhzh03a1hDlZnOFfgArkSg1gRtVXPHR+OQCUWnAH9Djzum0yoCcMRGbDt8ONIppCmL9WPwB77UEpPXmk91A3n3y3uuGbB2DO9pWy7jDDkbij34LvAjOiaEcMk6QmEUUA8FmmVb
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: fluxcdbot
      namespace: default

