apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fluxcdbot
  namespace: flux-system
spec:
  encryptedData:
    address: AgCDbvyACl290xD7KvdMaD8VbBmYmUbrUxWnhth5TDw697PfA3KaMhVLiBgNKOPy5W2WVk8eKe76ytjSGyVJ4E8pufQNQwNIJGTDt+D0T839RiGIslYgZaA6Kbc/d128OnpwRGyhRpbhcTxv94lVpcUQxw2fQg+npT+bBQERPQpMSO9zpTGYmo1+VsdhMJqSmKmAU1b1AYxkiFRFW7fxGDbjSimd73jJrrA7shr28CJPoTz0k2jIOP1GK/aE35Hnu+3khHjg0igKpIHzlKi7f84VVYPWJ6iod1DcCfTptw0pFI/FAWp04n9eplxjd0qojyvqzDEHTSKUNgKQOJz+eTeo25vY2y0f53K0/uz22rAu3pQDHFf6cWNd9mb4KvQ7m+nwXL/raqbJIV0VhtWnC7dYp8XPPfLexTdXZIWFgovL0qydjlzvRnXSth800g/2IgsgiG/eAncDOSeHxF+NXOhsWcdulgSgpdmkAKPJD98lUBVNw+fob5qwgY2J7rP5uqcv8fYygWNV2ggD8oZd6MoqdEqQ4hyi+UwBkS6GK4ZtlNqKdBVGnnPbckmmjBzXz0rtHsQrJRTLiQ7fGMM5kYUmNMrZ1lmbD1DVn33k/bNC2gQyjqkpok+X1cfdoPKq5CJd3yWNOU875UCNk39G9/pAhOgfDZpPYG9raJpVGWgCSPkWUifK9k8vyem9k8uQou6Ihc1DgnZ7O/yHCFGWUml6Oc/Gy8zb6jFz3/lcu0TqQZzerUbbljCXhui0F39SkYgjXs9nEHOq1YLGKcibeIcoYkQ7krdCTmwlYiKg96RriTPXNDhfasMgNx8HQY7o/dr3alKB7u3Y0jo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: fluxcdbot
      namespace: flux-system

