apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github
  namespace: flux-system
spec:
  encryptedData:
    token: AgCl5iU+tiCWh3AsWZi32XtkXNvr8WQNjccr1qlqWhKC3cWYHfj11CFWMXFfHRvwyiD97H7+Ucoxbe1oV/Y4Qp+2FE+RENmJizZpHDcBkaPYUAcINLz/4Ulu+3gXOtKkCYW/4NQ0D+waz/BmXOG6MxM4NEE4ClSmSL6s79vSUlpJzgOFnBlxRBZ4dYystPGhVJjRteukhgYMa65j7Sz7TwaNDMYETCZ19PDS9lnMcYkq+UcUAGOSyy2YZPoANgLdK3LWQmzdbLbj8nfzMDFbsXBpHn66tFQg0u6SX2nG+mSNqnA6xC1g16mNrHQxKmcPbfMr3cxXz6z+/dezvtUBvpKh2K3sGHSLNpmr2a6Mdt/zXqzk02+UakaOQ7Kvr5qf6fx/d+snWweT8PqXen9n6UirqzYKahjB7gT4jZom6yMvEd2lisrP9NpXuxkQ0RfHeFBGHadbtMPHvbdxZV7HqEGVK3w/tXEgCABJOc9fnwH75SczAcRTjuBujuyNQJLWzBMNIF9GK+AIkOmUjklvaRmdyHxhp8TT73i6dRknemf6F/YHK17mnsS3JuTFW5mcxi1VnuhhiStZoGcyWz0eBNkG2KXf93OUrvK5kKntVHgxXtXqZ0USIPG96WAvSz2e4HllBR2J9cPH+ECr26VYEYyHfvAM4wb2eQs57pJctNU5DDCSAshp8uCKi1aeNHDEZ0gzEkJBpYH9m0NeTiH41ljr4Kv+rqatEyyWWVkCWOWhqqyGc42GIF06
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github
      namespace: flux-system

