---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: github
  namespace: flux-system
spec:
  type: github
  address: https://github.com/pinguiorg/infrastructure
  secretRef:
    name: github
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: github-status
  namespace: flux-system
spec:
  providerRef:
    name: github
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: flux-system
      namespace: flux-system
    - kind: Kustomization
      name: services
      namespace: flux-system
    - kind: Kustomization
      name: apps
      namespace: flux-system
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: fluxcdbot
  namespace: flux-system
spec:
  type: generic
  secretRef:
    name: fluxcdbot
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: fluxcdbot
  namespace: flux-system
spec:
  providerRef:
    name: fluxcdbot
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: flux-system
      namespace: flux-system
    - kind: Kustomization
      name: services
      namespace: flux-system
    - kind: Kustomization
      name: apps
      namespace: flux-system
