apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager
  namespace: cert-manager
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgCj5idS6nGlFcTQ2n5myRfp4MLh7VzabcVBtCjvFOOXO9NOXshIc42mFcflTeVYx0hkwhD94sb85/15aA6LMp/v6qIFbp3fbQ5m1OmOWDnestHNAC5/fluOO/S4xZAgfvFX4xev3MqDRxl9B+VX2RcnmOdTXP2jJd/zH1ElpQ8CuiNzJ3jdezm26vuY1+RCsFmdQ3MTElUD6Qo8vlDu9seoLxGfgbDONlQ0RuUrmrJrwf76u+OG8Pg+H32JiHDgEZNUdeiQiypG/AlJSNSElbqk3AklXSXQOhhp4joWYo5nZRsapE2ecESN0pZk64l6y6WFicnAahvw26r4i8/qQryI6BE7LFDCUrCPR3M3yeo4lMzqJp3TqwunQLnwSCpQVgEW1ENqjfhK8azlZnNOJNfGSo3NCpYYAemlSXfmCD849KnzXFOHBoBOhvG0xf2jqyqW1bMdVkxjpl5e/YEpI/izXRTZ6gavJvoObtlf7gnG/KjTEPSFC3iw0/Ng/S75yylUp/PjK7rdVchN9P6E+uXM7dvlGrzemVQMULCeTmmh09jtDbEWb7gu2pNrUrXnHSm5b93RmeGrXLO9z/yBbFCKLD/NbMaX2OGV+3UkoShz5q1bFhBn7vLJ0MDxLruzYSY0WQRZuzy+/56W5bHtPDj4f6cax6Hcqzq9prY8/Jk47Fk5bORz7LfbJiuUkjbWPusKWROkH2kuKMDqvKO1bv3QkQUmkr2DWTHzYL4PwS8gcCOiWLX4cvbX
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cert-manager
      namespace: cert-manager

