apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: fluxcdbot
  name: fluxcdbot
spec:
  podMetricsEndpoints:
  - interval: 15s
    port: internal
    path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: fluxcdbot
