apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/monitoring
resources:
- manifests/alertmanager-secret-sealed.yaml
- manifests/grafana-dashboardDatasources-secret-sealed.yaml
- manifests/prometheus-roleSpecificNamespaces.yaml
- manifests/prometheus-roleBindingSpecificNamespaces.yaml
- manifests/kube-controller-manager-prometheus-discovery-service.yaml
- manifests/kube-scheduler-prometheus-discovery-service.yaml
patchesStrategicMerge:
- manifests/patch-alertmanager-secret-sealed.yaml
- manifests/patch-alertmanager-service.yaml
- manifests/patch-prometheus-service.yaml
- manifests/patch-prometheus-prometheus.yaml
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Prometheus
    name: k8s
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Alertmanager
    name: main
