apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: snapclient
    app.kubernetes.io/part-of: snapcast
  name: snapclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: snapclient
      app.kubernetes.io/part-of: snapcast
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snapclient
        app.kubernetes.io/part-of: snapcast
    spec:
      containers:
      - name: snapclient
        image: saiyato/snapclient
        command:
        - /usr/local/bin/snapclient
        - -h
        - snapserver
        - -p
        - $(SNAPSERVER_SERVICE_PORT_AUDIO)
