apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: snapcast.k.squat.ai
  labels:
    app.kubernetes.io/name: snapserver
    app.kubernetes.io/part-of: snapcast
  name: snapserver
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: snapserver
    app.kubernetes.io/part-of: snapcast
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: audio
    protocol: TCP
    port: 1704
    targetPort: audio
  - name: tcp
    protocol: TCP
    port: 1705
    targetPort: tcp
---
kind: Service
apiVersion: v1
metadata:
  name: snapserver-headless
  labels:
    app.kubernetes.io/name: snapserver
    app.kubernetes.io/part-of: snapcast
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: snapserver
    app.kubernetes.io/part-of: snapcast
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: audio
    protocol: TCP
    port: 1704
    targetPort: audio
  - name: tcp
    protocol: TCP
    port: 1705
    targetPort: tcp
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: snapserver
    app.kubernetes.io/part-of: snapcast
  name: snapserver
spec:
  replicas: 1
  serviceName: snapserver-headless
  selector:
    matchLabels:
      app.kubernetes.io/name: snapserver
      app.kubernetes.io/part-of: snapcast
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snapserver
        app.kubernetes.io/part-of: snapcast
    spec:
      containers:
      - name: snapserver
        image: saiyato/snapserver
        command:
        - /usr/local/bin/snapserver
        args: []
        ports:
        - name: http
          containerPort: 1780
        - name: audio
          containerPort: 1704
        - name: tcp
          containerPort: 1705
        volumeMounts:
        - name: fifo
          mountPath: /var/lib/fifo
      volumes:
      - name: fifo
        emptyDir: {}
