name: CI

on:
  push:
    branches: [ main ]
    tags:
      - "*"
  pull_request:
    branches: [ main ]
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Kubernetes tests
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: 4.2.0
          command: |
            CONTAINERIZE_TEST=false make test
