apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: snapcast
commonLabels:
  app.kubernetes.io/name: line-in
  app.kubernetes.io/part-of: line-in
resources:
- manifests/line-in.yaml
